"""
Network entities and registration.

Paper section 4 defines four layers and five entity types: the Trusted
Authority, CAVs, RSUs, MEC servers and a cloud server. Paper section 5.2
registers each of them.

DEVIATION D4 -- key escrow.

Paper section 5.2.2 reads: "The TA assigns a unique identifier ID_rsu_i to each
rsu_i. It then generates a private key sk_rsu_i and an error vector e_rsu_i ...
Upon receiving the message from the TA, rsu_i generates its own private key
sk_rsu_i from the same distribution and computes its corresponding public key."

Two problems. First, a TA that generates entity private keys holds every
decryption key, which is exactly the key escrow that the paper's own Table 2
claims the scheme avoids ("No key escrow" marked as satisfied). Second, keys
are generated twice, so the registration token S_rsu -- computed by the TA over
its own copy -- is bound to a public key the entity then discards.

Here each entity generates its own long-term keypair locally and the TA
certifies the public key only. The TA never sees a private key. This satisfies
the paper's stated security property rather than contradicting it.
"""

from __future__ import annotations

import os
import time
from dataclasses import dataclass, field
from enum import Enum

from .crypto import DEFAULT_SIG, H, registration_token


class Role(str, Enum):
    """Paper section 4: entities of the user, MEC, consensus and cloud layers."""

    VEHICLE = "CAV"
    RSU = "RSU"
    MEC = "MEC"
    CLOUD = "CLOUD"


class RegistrationError(Exception):
    """Enrolment or credential validation failed."""


# ---------------------------------------------------------------------------
# Entities
# ---------------------------------------------------------------------------

@dataclass
class Entity:
    """
    A CAV, RSU, MEC server or cloud server.

    sig_pk / sig_sk are the long-term ML-DSA identity keypair. The private key
    never leaves the entity -- for a vehicle it is held in the OBU (paper
    section 5.2.1).
    """

    identity: str
    role: Role
    sig_pk: bytes = field(default=b"", repr=False)
    sig_sk: bytes = field(default=b"", repr=False)
    token: bytes = field(default=b"", repr=False)
    ts: int = 0
    position: tuple[float, float] = (0.0, 0.0)

    # -- key management ----------------------------------------------------
    def generate_keys(self) -> None:
        """DEVIATION D4: generated by the entity, not by the TA."""
        self.sig_pk, self.sig_sk = DEFAULT_SIG.keygen()

    def sign(self, message: bytes) -> bytes:
        if not self.sig_sk:
            raise RegistrationError(f"{self.identity} has no signing key")
        return DEFAULT_SIG.sign(self.sig_sk, message)

    @staticmethod
    def verify(sig_pk: bytes, message: bytes, signature: bytes) -> bool:
        try:
            return DEFAULT_SIG.verify(sig_pk, message, signature)
        except Exception:
            return False

    # -- credential presented to a peer during handshake -------------------
    @property
    def credential(self) -> bytes:
        """Identity, certified public key and issue time, as signed by the TA."""
        return H(self.identity.encode(), self.sig_pk, str(self.ts).encode(), length=32)

    def is_registered(self) -> bool:
        return bool(self.token) and bool(self.sig_pk)


def make_vehicle(i: int) -> Entity:
    return Entity(f"CAV_{i:04d}", Role.VEHICLE)


def make_rsu(i: int, position: tuple[float, float] = (0.0, 0.0)) -> Entity:
    return Entity(f"RSU_{i:03d}", Role.RSU, position=position)


def make_mec(i: int) -> Entity:
    return Entity(f"MEC_{i:03d}", Role.MEC)


def make_cloud(i: int = 0) -> Entity:
    return Entity(f"CLOUD_{i:02d}", Role.CLOUD)


# ---------------------------------------------------------------------------
# Trusted Authority (paper sections 5.1 and 5.2)
# ---------------------------------------------------------------------------

class TrustedAuthority:
    """
    Publishes system parameters, enrols entities, and maintains a revocation
    list.

    Holds a master key MK used to compute registration tokens
    S_i = H(ID_i || pk_i || MK || TS_i). MK never leaves the TA and no entity
    private key is ever held here (DEVIATION D4).
    """

    #: freshness window for a presented timestamp, seconds (paper: T_delta)
    FRESHNESS_WINDOW = 300

    def __init__(self, freshness_window: int | None = None) -> None:
        self.master_key = os.urandom(32)
        self.directory: dict[str, bytes] = {}      # identity -> certified public key
        self.tokens: dict[str, tuple[bytes, int]] = {}
        self.revoked: set[str] = set()             # CRL
        if freshness_window is not None:
            self.FRESHNESS_WINDOW = freshness_window

    # -- enrolment ---------------------------------------------------------
    def enrol(self, entity: Entity) -> None:
        """
        Paper section 5.2: assign identity, certify public key, issue token.

        The entity must already hold its own keypair. The TA refuses to enrol
        an entity whose keys it would have to generate.
        """
        if not entity.sig_pk:
            raise RegistrationError(
                f"{entity.identity} must generate its own keypair before enrolment "
                "(deviation D4: the TA does not generate entity private keys)"
            )
        if entity.identity in self.directory:
            raise RegistrationError(f"{entity.identity} already enrolled")

        ts = int(time.time())
        token = registration_token(entity.identity, entity.sig_pk, self.master_key, ts)

        self.directory[entity.identity] = entity.sig_pk
        self.tokens[entity.identity] = (token, ts)
        entity.token, entity.ts = token, ts

    def enrol_all(self, entities: list[Entity]) -> None:
        for e in entities:
            if not e.sig_pk:
                e.generate_keys()
            self.enrol(e)

    # -- validation --------------------------------------------------------
    def verify_registration(
        self, identity: str, sig_pk: bytes, token: bytes, ts: int, now: int | None = None
    ) -> bool:
        """
        Validate a presented credential.

        Four checks, all required:
          1. the identity is not revoked (CRL, paper section 6.2)
          2. the presented public key matches the one the TA certified
          3. the token recomputes correctly under MK
          4. the timestamp is fresh (replay defence, paper section 5.3)
        """
        if identity in self.revoked:
            return False
        certified = self.directory.get(identity)
        if certified is None or certified != sig_pk:
            return False
        expected = registration_token(identity, sig_pk, self.master_key, ts)
        if expected != token:
            return False
        now = int(time.time()) if now is None else now
        if abs(now - ts) > self.FRESHNESS_WINDOW:
            return False
        return True

    def verify_entity(self, entity: Entity, now: int | None = None) -> bool:
        return self.verify_registration(
            entity.identity, entity.sig_pk, entity.token, entity.ts, now
        )

    def revoke(self, identity: str) -> None:
        self.revoked.add(identity)

    # -- published parameters (paper section 5.1) --------------------------
    @property
    def public_parameters(self) -> dict:
        from .crypto import DEFAULT_KEM_NAME, DEFAULT_SIG_NAME, SYSTEM_PARAMS

        return {
            **SYSTEM_PARAMS,
            "H": "SHAKE-256",
            "KDF": "SHAKE-256",
            "KEM": DEFAULT_KEM_NAME,
            "SIG": DEFAULT_SIG_NAME,
        }

    def __repr__(self) -> str:
        return (
            f"TrustedAuthority(enrolled={len(self.directory)}, "
            f"revoked={len(self.revoked)})"
        )
