"""Small elliptic-curve functions for the classroom demonstration."""

from math import gcd, isqrt
from typing import Dict, Optional, Tuple


Curve = Tuple[int, int, int]  # (field prime p, coefficient a, coefficient b)
Point = Optional[Tuple[int, int]]


def is_prime(number: int) -> bool:
    """Check whether a number is prime."""

    if number < 2:
        return False
    for divisor in range(2, isqrt(number) + 1):
        if number % divisor == 0:
            return False
    return True


def make_curve(p: int, a: int, b: int) -> Curve:
    """Create and validate y^2 = x^3 + ax + b modulo p."""

    if p <= 3 or not is_prime(p):
        raise ValueError("p must be a prime greater than 3")
    if (4 * a**3 + 27 * b**2) % p == 0:
        raise ValueError("the curve is singular")
    return p, a % p, b % p


def on_curve(curve: Curve, point: Point) -> bool:
    """Check whether a point belongs to the curve."""

    if point is None:
        return True

    p, a, b = curve
    x, y = point
    return 0 <= x < p and 0 <= y < p and (y * y - x**3 - a * x - b) % p == 0


def add_points(curve: Curve, point1: Point, point2: Point) -> Point:
    """Add two elliptic-curve points."""

    if not on_curve(curve, point1) or not on_curve(curve, point2):
        raise ValueError("point is not on the curve")
    if point1 is None:
        return point2
    if point2 is None:
        return point1

    p, a, _ = curve
    x1, y1 = point1
    x2, y2 = point2

    if x1 == x2 and (y1 + y2) % p == 0:
        return None

    if point1 == point2:
        slope = (3 * x1 * x1 + a) * pow(2 * y1, -1, p)
    else:
        slope = (y2 - y1) * pow(x2 - x1, -1, p)

    slope %= p
    x3 = (slope * slope - x1 - x2) % p
    y3 = (slope * (x1 - x3) - y1) % p
    return x3, y3


def multiply(curve: Curve, number: int, point: Point) -> Point:
    """Calculate number * point using repeated doubling."""

    result = None
    current = point

    while number > 0:
        if number % 2 == 1:
            result = add_points(curve, result, current)
        current = add_points(curve, current, current)
        number //= 2

    return result


def point_order(curve: Curve, point: Point) -> int:
    """Find the first n for which nG is the point at infinity."""

    if point is None or not on_curve(curve, point):
        raise ValueError("G must be a point on the curve")

    p = curve[0]
    result = None
    limit = p + 1 + 2 * isqrt(p)  # Hasse bound

    for order in range(1, limit + 1):
        result = add_points(curve, result, point)
        if result is None:
            return order

    raise ValueError("could not find the order of G")


def create_keypair(curve: Curve, generator: Point, private_key: int):
    """Return the order of G and public point Q = dG."""

    order = point_order(curve, generator)
    if not 1 <= private_key < order:
        raise ValueError(f"d must satisfy 1 <= d < {order}")
    if gcd(private_key, order) != 1:
        raise ValueError("d must be coprime with the order of G")

    public_key = multiply(curve, private_key, generator)
    return order, public_key


def encrypt(curve: Curve, generator: Point, public_key: Point,
            order: int, message: int, one_time_key: int) -> Dict[str, object]:
    """Encrypt a small message using educational EC ElGamal."""

    if not 1 <= message < order:
        raise ValueError(f"m must satisfy 1 <= m < {order}")
    if not 1 <= one_time_key < order or gcd(one_time_key, order) != 1:
        raise ValueError(f"k must be coprime with {order} and satisfy 1 <= k < {order}")

    message_point = multiply(curve, message, generator)
    c1 = multiply(curve, one_time_key, generator)
    shared_point = multiply(curve, one_time_key, public_key)
    c2 = add_points(curve, message_point, shared_point)

    return {"message_point": message_point, "shared": shared_point,
            "c1": c1, "c2": c2}


def decrypt(curve: Curve, c1: Point, c2: Point, private_key: int) -> Point:
    """Recover M = C2 - dC1."""

    shared_point = multiply(curve, private_key, c1)
    if shared_point is None:
        return c2

    negative_shared = shared_point[0], (-shared_point[1]) % curve[0]
    return add_points(curve, c2, negative_shared)


def decode_message(curve: Curve, generator: Point, order: int,
                   message_point: Point) -> int:
    """Convert the toy point M = mG back to the small integer m."""

    for message in range(1, order):
        if multiply(curve, message, generator) == message_point:
            return message
    raise ValueError("message point is not generated by G")


def show_point(point: Point) -> str:
    """Format a point for the console."""

    return "O" if point is None else f"({point[0]}, {point[1]})"
