"""Classical demonstration of Shor's threat to ECC."""

from typing import Dict, List, Tuple

from .ecc import Curve, Point, decode_message, decrypt, multiply


def find_private_key(curve: Curve, generator: Point, public_key: Point,
                     order: int) -> Tuple[int, List[Tuple[int, Point]]]:
    """Find d in Q = dG with a small classical loop."""

    steps = []

    for candidate in range(1, order):
        point = multiply(curve, candidate, generator)
        steps.append((candidate, point))

        if point == public_key:
            return candidate, steps

    raise ValueError("public key is not generated by G")


def attack_ecc(curve: Curve, generator: Point, public_key: Point,
               order: int, c1: Point, c2: Point) -> Dict[str, object]:
    """Recover d and the message using only public ECC information."""

    recovered_d, steps = find_private_key(curve, generator, public_key, order)
    message_point = decrypt(curve, c1, c2, recovered_d)
    message = decode_message(curve, generator, order, message_point)

    return {"d": recovered_d, "steps": steps,
            "message_point": message_point, "message": message}
