"""Classical demonstration of the ECC discrete-log step threatened by Shor.

No quantum computation occurs. Exhaustive point multiplication replaces the
quantum discrete-logarithm subroutine so the attack structure is visible on a
tiny curve.
"""

from dataclasses import dataclass

from .ecc import (
    Curve,
    ECCCiphertext,
    Point,
    decode_message_scalar,
    decrypt_point,
    scalar_multiply,
)


@dataclass(frozen=True)
class ECCDiscreteLogStep:
    """One candidate scalar and the curve point it produces."""

    candidate: int
    candidate_point: Point


@dataclass(frozen=True)
class ECCShorAttackResult:
    """Private and plaintext values reconstructed from public ECC information."""

    recovered_private_scalar: int
    recovered_message_point: Point
    recovered_message_scalar: int
    search_trace: tuple[ECCDiscreteLogStep, ...]


def recover_private_scalar_classically(
    curve: Curve,
    generator: Point,
    generator_order: int,
    public_point: Point,
) -> tuple[int, tuple[ECCDiscreteLogStep, ...]]:
    """Solve ``Q = dG`` by exhaustive search for a tiny educational curve."""

    if not curve.contains(generator) or generator is None:
        raise ValueError("G must be a finite point on the curve")
    if not curve.contains(public_point) or public_point is None:
        raise ValueError("Q must be a finite point on the curve")
    if generator_order < 2 or scalar_multiply(curve, generator_order, generator) is not None:
        raise ValueError("the supplied generator order is invalid")

    trace: list[ECCDiscreteLogStep] = []
    for candidate in range(1, generator_order):
        candidate_point = scalar_multiply(curve, candidate, generator)
        trace.append(ECCDiscreteLogStep(candidate, candidate_point))
        if candidate_point == public_point:
            return candidate, tuple(trace)
    raise ValueError("public point Q is not in the subgroup generated by G")


def run_ecc_shor_math_attack(
    curve: Curve,
    generator: Point,
    generator_order: int,
    public_point: Point,
    ciphertext: ECCCiphertext,
) -> ECCShorAttackResult:
    """Recover ECC private data using only public/intercepted values.

    The legitimate private scalar, message, and ephemeral scalar are not
    parameters and cannot be read by this attacker-side function.
    """

    recovered_private, trace = recover_private_scalar_classically(
        curve, generator, generator_order, public_point
    )
    recovered_point = decrypt_point(curve, ciphertext, recovered_private)
    recovered_message = decode_message_scalar(
        curve, generator, generator_order, recovered_point
    )
    return ECCShorAttackResult(
        recovered_private,
        recovered_point,
        recovered_message,
        trace,
    )
